// ReSharper disable All
using System;
using System.Diagnostics.CodeAnalysis;
using RE_Editor.Models.Enums;

namespace RE_Editor.Constants;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "IdentifierTypo")]
public static class OtomoArmorLayeredConstants {
    public const int ASHIGARU_GUARD = 86;
    public const int ASHIGARU_HELM = 85;
    public const int ATHOSS_ARMOR_Α = 80;
    public const int ATHOSS_SCAR_Α = 79;
    public const int BLANKA_CHAN_BODY_Α = 126;
    public const int BLANKA_CHAN_HEAD_Α = 125;
    public const int F_AJARAKAN_HELM_Α = 33;
    public const int F_AJARAKAN_MAIL_Α = 34;
    public const int F_BUTTERFLY_HAT_Α = 109;
    public const int F_BUTTERFLY_VEST_Α = 110;
    public const int F_CABRA_HOOD_Α = 7;
    public const int F_CABRA_JUMPSUIT_Α = 8;
    public const int F_DOSHAGUMA_HELM_Α = 31;
    public const int F_DOSHAGUMA_MAIL_Α = 32;
    public const int F_GUARDIAN_ARK_HELM_Α = 59;
    public const int F_GUARDIAN_ARK_MAIL_Α = 60;
    public const int F_GUARDIAN_DOSHA_HELM_Α = 35;
    public const int F_GUARDIAN_DOSHA_MAIL_Α = 36;
    public const int F_GUARDIAN_EBONY_HELM_Α = 39;
    public const int F_GUARDIAN_EBONY_MAIL_Α = 40;
    public const int F_GUARDIAN_FULGUR_HELM_Α = 29;
    public const int F_GUARDIAN_FULGUR_MAIL_Α = 30;
    public const int F_GUARDIAN_RATH_HELM_Α = 37;
    public const int F_GUARDIAN_RATH_MAIL_Α = 38;
    public const int F_MIZUTSUNE_KASA_Α = 87;
    public const int F_MIZUTSUNE_SUIT_Α = 88;
    public const int F_NUMINOUS_CROWN_Α = 89;
    public const int F_NUMINOUS_ROBE_Α = 90;
    public const int F_PAPIER_MÂCHÉ_BODY_Α = 108;
    public const int F_PAPIER_MÂCHÉ_HEAD_Α = 107;
    public const int F_ROMPOPOLO_BRAIN_Α = 19;
    public const int F_ROMPOPOLO_SUIT_Α = 20;
    public const int FELYNE_ALLOY_HELM_Α = 5;
    public const int FELYNE_ALLOY_MAIL_Α = 6;
    public const int FELYNE_ARKVELD_HELM_Α = 61;
    public const int FELYNE_ARKVELD_MAIL_Α = 62;
    public const int FELYNE_ARTIAN_CORE_Α = 77;
    public const int FELYNE_ARTIAN_GEAR_Α = 78;
    public const int FELYNE_AZUZ_BODY_Α = 72;
    public const int FELYNE_AZUZ_HEAD_Α = 71;
    public const int FELYNE_BALAHARA_HELM_Α = 21;
    public const int FELYNE_BALAHARA_MECH_Α = 22;
    public const int FELYNE_BARINA_DRESS_Α = 12;
    public const int FELYNE_BARINA_WIG_Α = 11;
    public const int FELYNE_BLANGO_BODY_Α = 44;
    public const int FELYNE_BLANGO_HEAD_Α = 43;
    public const int FELYNE_BONE_HELM_Α = 3;
    public const int FELYNE_BONE_MAIL_Α = 4;
    public const int FELYNE_CONGA_FETE_Α = 14;
    public const int FELYNE_CONGA_HEAD_Α = 13;
    public const int FELYNE_DAHAAD_CORONA_Α = 49;
    public const int FELYNE_DAHAAD_GOWN_Α = 50;
    public const int FELYNE_DAU_ARMOR_Α = 52;
    public const int FELYNE_DAU_ARMOR_Γ = 98;
    public const int FELYNE_DAU_HELM_Α = 51;
    public const int FELYNE_DAU_HELM_Γ = 97;
    public const int FELYNE_DEATHGEAR_COWL_Α = 64;
    public const int FELYNE_DEATHGEAR_HOOD_Α = 63;
    public const int FELYNE_DUFFEL_COAT = 84;
    public const int FELYNE_DUFFEL_HOOD = 83;
    public const int FELYNE_DUNA_CAPE_Α = 54;
    public const int FELYNE_DUNA_MASK_Α = 53;
    public const int FELYNE_GORE_GHOST_Α = 58;
    public const int FELYNE_GORE_HORROR_Α = 57;
    public const int FELYNE_GRAV_ARMOR_Α = 48;
    public const int FELYNE_GRAV_MASK_Α = 47;
    public const int FELYNE_GYPCEROS_CREST_Α = 17;
    public const int FELYNE_GYPCEROS_TUNIC_Α = 18;
    public const int FELYNE_HIRABAMI_CAP_Α = 25;
    public const int FELYNE_HIRABAMI_ROBE_Α = 26;
    public const int FELYNE_HOPE_HELM_Α = 1;
    public const int FELYNE_HOPE_SUIT_Α = 2;
    public const int FELYNE_KUNAFA_HOOD_Α = 67;
    public const int FELYNE_KUNAFA_SUIT_Α = 68;
    public const int FELYNE_KUT_KU_MASK_Α = 15;
    public const int FELYNE_KUT_KU_WEAR_Α = 16;
    public const int FELYNE_LEATHER_CAP = 81;
    public const int FELYNE_LEATHER_VEST = 82;
    public const int FELYNE_QUEMA_HELM_Α = 9;
    public const int FELYNE_QUEMA_MAIL_Α = 10;
    public const int FELYNE_RATHALOS_HELM_Α = 45;
    public const int FELYNE_RATHALOS_MAIL_Α = 46;
    public const int FELYNE_RATHIAN_MAIL_Α = 28;
    public const int FELYNE_RATHIAN_TIARA_Α = 27;
    public const int FELYNE_SCYLLA_MAIL_Α = 24;
    public const int FELYNE_SCYLLA_MASK_Α = 23;
    public const int FELYNE_SILD_HOOD_Α = 75;
    public const int FELYNE_SILD_SUIT_Α = 76;
    public const int FELYNE_SUJA_FROG_Α = 73;
    public const int FELYNE_SUJA_VEST_Α = 74;
    public const int FELYNE_UDRA_HEAD_Α = 55;
    public const int FELYNE_UDRA_TENTACLES_Α = 56;
    public const int FELYNE_XU_WU_SUIT_Α = 42;
    public const int FELYNE_XU_WU_VEIL_Α = 41;
    public const int WACKY_WUDWUD_BODY_Α = 132;
    public const int WACKY_WUDWUD_MASK_Α = 131;
    public const int WUDWUD_BODY_Α = 70;
    public const int WUDWUD_MASK_Α = 69;
}
