// ReSharper disable All
using System;
using System.Diagnostics.CodeAnalysis;
using RE_Editor.Models.Enums;

namespace RE_Editor.Constants;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "IdentifierTypo")]
public static class PendantConstants {
    public const App_WeaponCharmDef_TYPE_Fixed ARKVELD__MARK_OF_RESOLVE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0005;
    public const App_WeaponCharmDef_TYPE_Fixed AVIAN_WIND_CHIME = App_WeaponCharmDef_TYPE_Fixed.CHARM_0007;
    public const App_WeaponCharmDef_TYPE_Fixed AZUZ__MARK_OF_GRATITUDE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0006;
    public const App_WeaponCharmDef_TYPE_Fixed BARREL_BOWLING_STRAP = App_WeaponCharmDef_TYPE_Fixed.CHARM_0105;
    public const App_WeaponCharmDef_TYPE_Fixed BARREL_BOWLING_TROPHY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0104;
    public const App_WeaponCharmDef_TYPE_Fixed BLACK_CAT_BELL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0035;
    public const App_WeaponCharmDef_TYPE_Fixed BLANKA_CHAN_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0098;
    public const App_WeaponCharmDef_TYPE_Fixed BLUE_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0040;
    public const App_WeaponCharmDef_TYPE_Fixed BLUE_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0044;
    public const App_WeaponCharmDef_TYPE_Fixed BLUE_LALA_DRESS_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0092;
    public const App_WeaponCharmDef_TYPE_Fixed BLUE_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0058;
    public const App_WeaponCharmDef_TYPE_Fixed COMMON_WOOD_MINNOW = App_WeaponCharmDef_TYPE_Fixed.CHARM_0144;
    public const App_WeaponCharmDef_TYPE_Fixed DANCING_BLACK_CAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0096;
    public const App_WeaponCharmDef_TYPE_Fixed DANCING_WHITE_CAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0001;
    public const App_WeaponCharmDef_TYPE_Fixed DOSHAGUMA__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0080;
    public const App_WeaponCharmDef_TYPE_Fixed DOSHAGUMA__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0079;
    public const App_WeaponCharmDef_TYPE_Fixed DOSHAGUMA__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0081;
    public const App_WeaponCharmDef_TYPE_Fixed DRAGONTORCH_WINGS = App_WeaponCharmDef_TYPE_Fixed.CHARM_0004;
    public const App_WeaponCharmDef_TYPE_Fixed DREAMSPELL_FELYNE_TEDDY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0101;
    public const App_WeaponCharmDef_TYPE_Fixed DUSTER_RIG = App_WeaponCharmDef_TYPE_Fixed.CHARM_0148;
    public const App_WeaponCharmDef_TYPE_Fixed EMERALD_JITTERBAIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0146;
    public const App_WeaponCharmDef_TYPE_Fixed FELYNE_CARAMEL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0107;
    public const App_WeaponCharmDef_TYPE_Fixed FELYNE_DUNA_BOBBLE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0003;
    public const App_WeaponCharmDef_TYPE_Fixed FELYNE_DUNA_Γ_BOBBLE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0150;
    public const App_WeaponCharmDef_TYPE_Fixed FELYNE_MINT_CHOCOLATE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0106;
    public const App_WeaponCharmDef_TYPE_Fixed FELYNE_STRAWBERRY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0108;
    public const App_WeaponCharmDef_TYPE_Fixed FLAMEFETE_FELYNE_TEDDY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0100;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_DOODLES = App_WeaponCharmDef_TYPE_Fixed.CHARM_0135;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_HEARTS = App_WeaponCharmDef_TYPE_Fixed.CHARM_0134;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_HONEY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0138;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_OMG = App_WeaponCharmDef_TYPE_Fixed.CHARM_0129;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_POTIONS = App_WeaponCharmDef_TYPE_Fixed.CHARM_0139;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_SPARKLES = App_WeaponCharmDef_TYPE_Fixed.CHARM_0136;
    public const App_WeaponCharmDef_TYPE_Fixed FLOATING_WELL_DONE_STEAKS = App_WeaponCharmDef_TYPE_Fixed.CHARM_0137;
    public const App_WeaponCharmDef_TYPE_Fixed FLUTTERING_MYRIADS = App_WeaponCharmDef_TYPE_Fixed.CHARM_0123;
    public const App_WeaponCharmDef_TYPE_Fixed FLUTTERING_QUATREFLIES = App_WeaponCharmDef_TYPE_Fixed.CHARM_0122;
    public const App_WeaponCharmDef_TYPE_Fixed GOLDEN_BUGHEAD = App_WeaponCharmDef_TYPE_Fixed.CHARM_0145;
    public const App_WeaponCharmDef_TYPE_Fixed GREEN_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0039;
    public const App_WeaponCharmDef_TYPE_Fixed GREEN_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0046;
    public const App_WeaponCharmDef_TYPE_Fixed GREEN_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0059;
    public const App_WeaponCharmDef_TYPE_Fixed HAPPY_GO_CONGAKART = App_WeaponCharmDef_TYPE_Fixed.CHARM_0169;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__BLACK = App_WeaponCharmDef_TYPE_Fixed.CHARM_0025;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__BLUE_RED = App_WeaponCharmDef_TYPE_Fixed.CHARM_0023;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__GRAPE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0026;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__HAZARD = App_WeaponCharmDef_TYPE_Fixed.CHARM_0027;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__MONOCHROME = App_WeaponCharmDef_TYPE_Fixed.CHARM_0024;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__PINK_BLACK = App_WeaponCharmDef_TYPE_Fixed.CHARM_0029;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_G__PINK_BLUE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0028;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__BLUE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0018;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__GREEN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0017;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__MARMALADE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0016;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__PASTEL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0022;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__PURPLE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0019;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__RED_GREEN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0021;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF_S__SLATE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0020;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__BROWN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0013;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__CRIMSON = App_WeaponCharmDef_TYPE_Fixed.CHARM_0010;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__GREEN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0012;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__LIGHT_BLUE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0011;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__PEACH = App_WeaponCharmDef_TYPE_Fixed.CHARM_0015;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__SAFFRON = App_WeaponCharmDef_TYPE_Fixed.CHARM_0014;
    public const App_WeaponCharmDef_TYPE_Fixed HOPE_SCARF__TEAL_ORANGE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0009;
    public const App_WeaponCharmDef_TYPE_Fixed KUT_KU_PLUSHIE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0000;
    public const App_WeaponCharmDef_TYPE_Fixed LAGIACRUS_PLUSHIE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0160;
    public const App_WeaponCharmDef_TYPE_Fixed MIZUTSUNE__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0086;
    public const App_WeaponCharmDef_TYPE_Fixed MIZUTSUNE__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0085;
    public const App_WeaponCharmDef_TYPE_Fixed MIZUTSUNE__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0087;
    public const App_WeaponCharmDef_TYPE_Fixed NU_UDRA__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0113;
    public const App_WeaponCharmDef_TYPE_Fixed NU_UDRA__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0112;
    public const App_WeaponCharmDef_TYPE_Fixed NU_UDRA__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0114;
    public const App_WeaponCharmDef_TYPE_Fixed ORANGE_LALA_DRESS_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0094;
    public const App_WeaponCharmDef_TYPE_Fixed ORANGE_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0056;
    public const App_WeaponCharmDef_TYPE_Fixed PINK_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0042;
    public const App_WeaponCharmDef_TYPE_Fixed PINK_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0047;
    public const App_WeaponCharmDef_TYPE_Fixed PINK_LALA_DRESS_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0093;
    public const App_WeaponCharmDef_TYPE_Fixed RED_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0038;
    public const App_WeaponCharmDef_TYPE_Fixed RED_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0043;
    public const App_WeaponCharmDef_TYPE_Fixed RED_LALA_DRESS_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0091;
    public const App_WeaponCharmDef_TYPE_Fixed RED_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0060;
    public const App_WeaponCharmDef_TYPE_Fixed REY_DAU__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0083;
    public const App_WeaponCharmDef_TYPE_Fixed REY_DAU__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0082;
    public const App_WeaponCharmDef_TYPE_Fixed REY_DAU__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0084;
    public const App_WeaponCharmDef_TYPE_Fixed ROLLING_POOGIE__MONOCHROME = App_WeaponCharmDef_TYPE_Fixed.CHARM_0162;
    public const App_WeaponCharmDef_TYPE_Fixed ROLLING_POOGIE__TWO_TONE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0161;
    public const App_WeaponCharmDef_TYPE_Fixed SAKURA_FELYNE_TEDDY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0099;
    public const App_WeaponCharmDef_TYPE_Fixed SAKURA_POSY__COLORFUL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0032;
    public const App_WeaponCharmDef_TYPE_Fixed SAKURA_POSY__WHITE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0031;
    public const App_WeaponCharmDef_TYPE_Fixed SEREGIOS__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0110;
    public const App_WeaponCharmDef_TYPE_Fixed SEREGIOS__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0109;
    public const App_WeaponCharmDef_TYPE_Fixed SEREGIOS__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0111;
    public const App_WeaponCharmDef_TYPE_Fixed STRETCHED_BLACK_CAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0097;
    public const App_WeaponCharmDef_TYPE_Fixed STRETCHED_WHITE_CAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0002;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__AMSTRIGIAN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0049;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__COLOR = App_WeaponCharmDef_TYPE_Fixed.CHARM_0054;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__CYPURRPUNK = App_WeaponCharmDef_TYPE_Fixed.CHARM_0051;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__GOLD = App_WeaponCharmDef_TYPE_Fixed.CHARM_0052;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__HYMSTRIGIAN = App_WeaponCharmDef_TYPE_Fixed.CHARM_0050;
    public const App_WeaponCharmDef_TYPE_Fixed STRIGIBLE__LOVE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0053;
    public const App_WeaponCharmDef_TYPE_Fixed STUFFED_FELYNE_TEDDY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0008;
    public const App_WeaponCharmDef_TYPE_Fixed TENTACLE_JIG = App_WeaponCharmDef_TYPE_Fixed.CHARM_0149;
    public const App_WeaponCharmDef_TYPE_Fixed TROT_ALONG_CACTUAR = App_WeaponCharmDef_TYPE_Fixed.CHARM_0133;
    public const App_WeaponCharmDef_TYPE_Fixed TROT_ALONG_CRAKE = App_WeaponCharmDef_TYPE_Fixed.CHARM_0132;
    public const App_WeaponCharmDef_TYPE_Fixed TUFF_JOINT_BAIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0147;
    public const App_WeaponCharmDef_TYPE_Fixed UTH_DUNA__MARK_OF_BRAVERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0089;
    public const App_WeaponCharmDef_TYPE_Fixed UTH_DUNA__MARK_OF_CONTEST = App_WeaponCharmDef_TYPE_Fixed.CHARM_0088;
    public const App_WeaponCharmDef_TYPE_Fixed UTH_DUNA__MARK_OF_MASTERY = App_WeaponCharmDef_TYPE_Fixed.CHARM_0090;
    public const App_WeaponCharmDef_TYPE_Fixed VIOLET_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0041;
    public const App_WeaponCharmDef_TYPE_Fixed VIOLET_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0045;
    public const App_WeaponCharmDef_TYPE_Fixed VIOLET_LALA_DRESS_DOLL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0095;
    public const App_WeaponCharmDef_TYPE_Fixed VIOLET_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0057;
    public const App_WeaponCharmDef_TYPE_Fixed WELL_DONE_STEAK_STRAP = App_WeaponCharmDef_TYPE_Fixed.CHARM_0173;
    public const App_WeaponCharmDef_TYPE_Fixed WHITE_CAT_BELL = App_WeaponCharmDef_TYPE_Fixed.CHARM_0034;
    public const App_WeaponCharmDef_TYPE_Fixed WHITE_FAIRY_LIGHT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0037;
    public const App_WeaponCharmDef_TYPE_Fixed WHITE_FLAMEFETE_SPIRIT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0048;
    public const App_WeaponCharmDef_TYPE_Fixed WHITE_POLTERCAT = App_WeaponCharmDef_TYPE_Fixed.CHARM_0055;
}
