//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE_Editor.Data.MHWS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RE_Editor.Data.MHWS.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("ARMOR_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_LAYERED_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("ARMOR_LAYERED_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_LAYERED_NAME_LOOKUP_BY_VALUE {
            get {
                object obj = ResourceManager.GetObject("ARMOR_LAYERED_NAME_LOOKUP_BY_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_SERIES_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("ARMOR_SERIES_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARMOR_SERIES_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("ARMOR_SERIES_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARTIAN_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("ARTIAN_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DECORATION_INFO_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("DECORATION_INFO_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DECORATION_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("DECORATION_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("DLC_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("DLC_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ENEMY_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("ENEMY_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GIMMICK_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("GIMMICK_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GIMMICK_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("GIMMICK_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GP_CRC_OVERRIDE_INFO {
            get {
                object obj = ResourceManager.GetObject("GP_CRC_OVERRIDE_INFO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITEM_DESC_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ITEM_DESC_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITEM_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("ITEM_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITEM_NAME_LOOKUP {
            get {
                object obj = ResourceManager.GetObject("ITEM_NAME_LOOKUP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MEDAL_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("MEDAL_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MEDAL_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("MEDAL_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MENU_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("MENU_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MENU_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("MENU_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPC_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("NPC_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OBSOLETE_BY_HASH {
            get {
                object obj = ResourceManager.GetObject("OBSOLETE_BY_HASH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_ARMOR_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("OTOMO_ARMOR_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_LAYERED_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("OTOMO_LAYERED_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_LAYERED_NAME_LOOKUP_BY_VALUE {
            get {
                object obj = ResourceManager.GetObject("OTOMO_LAYERED_NAME_LOOKUP_BY_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("OTOMO_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_SERIES_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("OTOMO_SERIES_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_SERIES_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("OTOMO_SERIES_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OTOMO_WEAPON_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("OTOMO_WEAPON_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PENDANT_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("PENDANT_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PENDANT_NAME_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("PENDANT_NAME_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QUEST_INFO_LOOKUP_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("QUEST_INFO_LOOKUP_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SKILL_NAME_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("SKILL_NAME_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] STRUCT_INFO {
            get {
                object obj = ResourceManager.GetObject("STRUCT_INFO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TALISMAN_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("TALISMAN_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TITLE_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("TITLE_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TRANSLATION_App_EnemyDef_ID_BIT {
            get {
                object obj = ResourceManager.GetObject("TRANSLATION_App_EnemyDef_ID_BIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEAPON_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("WEAPON_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEAPON_LAYERED_INFO_LOOKUP_BY_GUID {
            get {
                object obj = ResourceManager.GetObject("WEAPON_LAYERED_INFO_LOOKUP_BY_GUID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEAPON_SERIES_BY_ENUM_VALUE {
            get {
                object obj = ResourceManager.GetObject("WEAPON_SERIES_BY_ENUM_VALUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
